name: calculadora_dart_dio
description: Uma calculadora usando o aprendizado da Formação Flutter da DIO.
version: 3.0.0
repository: https://github.com/GustavoCruz13/Calculadora-DIO

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
